[package]
name = "app"
version = "0.1.0"
description = "Lost Ark DPS Meter written in Rust"
authors = ["Snow"]
license = "GNU General Public License v3.0"
repository = "https://github.com/snoww/loa-logs"
default-run = "app"
edition = "2021"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3.0", features = [ "http-all", "clipboard-all", "fs-copy-file", "fs-read-file", "global-shortcut-all", "path-all", "process-command-api", "process-relaunch", "protocol-asset", "shell-open", "system-tray", "updater", "window-hide", "window-maximize", "window-minimize", "window-set-always-on-top", "window-set-focus", "window-set-ignore-cursor-events", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
lazy_static = "1.4.0"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
bitflags = "2.4.1"
window-vibrancy = "0.4.3"
hashbrown = { version = "0.14.3", features = ["serde"] }
rusqlite = { version = "0.32.1", features = ["bundled", "serde_json"] }
tokio = { version = "1.29.1", features = ["rt", "macros"] }
serde_with = "3.5.1"
log = "0.4.18"
flexi_logger = { version = "0.28.0", default-features = false }
reqwest = { version = "0.12", features = ["json"] }
md5 = "0.7.0"
async-recursion = "1.1.0"
uuid = { version = "1.8.0", features = ["v4"] }
moka = { version = "0.12.7", features = ["sync"] }
auto-launch = "0.5.0"
rsntp = { version = "4.0.0", default-features = false, features = ["chrono"]  }
flate2 = "1.0.30"
meter-core = { path = "E:\\Projects\\meter-core-rs\\" }
sysinfo = "0.31.4"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols

[profile.dev.package."*"]
debug = false # Disable debug symbols for dependencies

[patch.crates-io]
# Waiting for https://github.com/libpnet/libpnet/pull/715 to be adressed
pnet = { git = "https://github.com/anyduck/libpnet", branch = "fix-non-utf8-string" }
